services:
  - type: web
    name: khicho-chatbot
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      # SPA rewrite rule to route all frontend paths to index.html
      - type: rewrite
        source: /*
        destination: /index.html
